In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

A chi-square statistic is one way to show a relationship between two categorical variables

In [4]:
categories = ['aries','taurus','gemini','cancer','leo','virgo','libra','scorpio','sagittarius','capricorn',
             'aquarius','pisces']
observed = np.array([29,24,22,19,21,18,19,20,23,18,20,23])
print(len(categories))
print(len(observed))

12
12


A chi-square statistic is one way to show a relationship between two categorical variables. In statistics, there are two types of variables: numerical (countable) variables and non-numerical (categorical) variables. The chi-squared statistic is a single number that tells you how much difference exists between your observed counts and the counts you would expect if there were no relationship at all in the population.

A low value for chi-square means there is a high correlation between your two sets of data. In theory, if your observed and expected values were equal (“no difference”) then chi-square would be zero — an event that is unlikely to happen in real life. Deciding whether a chi-square test statistic is large enough to indicate a statistically significant difference isn’t as easy it seems. It would be nice if we could say a chi-square test statistic >10 means a difference, but unfortunately that isn’t the case.

Sample question: 256 visual artists were surveyed to find out their zodiac sign. 

The results were: Aries (29), Taurus (24), Gemini (22), Cancer (19), Leo (21), Virgo (18), Libra (19), Scorpio (20), Sagittarius (23), Capricorn (18), Aquarius (20), Pisces (23). 

Test the hypothesis that zodiac signs are evenly distributed across visual artists.

if the hypothesis is > 10. we can assumed it was not distributed evenly.

In [7]:
expected = np.tile(np.mean(observed),len(categories))
expected

array([ 21.33333333,  21.33333333,  21.33333333,  21.33333333,
        21.33333333,  21.33333333,  21.33333333,  21.33333333,
        21.33333333,  21.33333333,  21.33333333,  21.33333333])

In [8]:
residual = observed - expected
residual

array([ 7.66666667,  2.66666667,  0.66666667, -2.33333333, -0.33333333,
       -3.33333333, -2.33333333, -1.33333333,  1.66666667, -3.33333333,
       -1.33333333,  1.66666667])

In [9]:
component = np.square(residual) / expected
component

array([ 2.75520833,  0.33333333,  0.02083333,  0.25520833,  0.00520833,
        0.52083333,  0.25520833,  0.08333333,  0.13020833,  0.52083333,
        0.08333333,  0.13020833])

In [10]:
np.sum(component)

5.0937500000000009