In [1]:
import numpy as np
import cv2

In [4]:
#create 1D black image 
black = np.zeros([150,200,1],'uint8')
cv2.imshow("Black",black)
print(black[0,0,:]) #single channel value

cv2.waitKey(0)
cv2.destroyAllWindows()


[0]


In [5]:
black.shape

(150, 200, 1)

In [8]:
ones = np.ones([150,200,3],'uint8') #3dimension
cv2.imshow("Ones",ones)
print(ones[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[1 1 1]


In [11]:
white = np.ones([150,200,3],'uint16')
white *= (2**16-1) #uint16	0 to 65535 multiple white ones with maximum values
cv2.imshow("White",white)
print(white[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[65535 65535 65535]


In [12]:
2**16-1


65535

In [15]:
color = ones.copy()
color[:,:,:] = (255,0,0)
cv2.imshow("Blue",color)
print(color[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[255   0   0]


In [16]:
color.shape

(150, 200, 3)